### ISSUE TITLE
libSceBgft isnt Supported??

### ISSUE THREAD

**Issue by LightningMods** [flatz/ps4_stub_lib_maker_v2#3]
as per the write-up"

RESOLVE_NID(bgft_mid, sceBgftInitialize, "libSceBgft", "BZ0olR8Da0g");
RESOLVE_NID(bgft_mid, sceBgftDownloadRegisterTaskByStorageEx, "libSceBgft", "nd+0DEOC68A");
RESOLVE_NID(bgft_mid, sceBgftDownloadStartTask, "libSceBgft", "HRDHLMA9Y7s");
RESOLVE_NID(bgft_mid, sceBgftDownloadGetProgress, "libSceBgft", "5txx+w0HYOs");

i tried

![image](https://user-images.githubusercontent.com/34066913/55061398-0ef12f00-504a-11e9-9f19-b7acf6000593.png)

and added the Stub to my project but get PRX FUNCTION NOT RESOLVED ERROR

![image](https://user-images.githubusercontent.com/34066913/55061512-51b30700-504a-11e9-8627-6da3c99b5d92.png)

It failed trying to resolve sceBgftInitialize (the first function)

**Comment by flatz** [comment]
You need to load BGFT module manually I think:
```
#define SCE_SYSMODULE_INTERNAL_BGFT 0x8000002A
sceSysmoduleLoadModuleInternal(SCE_SYSMODULE_INTERNAL_BGFT);
```
